In [1]:
import pandas as pd
from utils import getSubset
import torch
import torch.nn as nn
import numpy as np
import pickle
import gzip

In [11]:
class linear(nn.Module):
    def __init__(self) -> None:
        super(linear, self).__init__()
        self.li1 = nn.Linear(5, 36)
        self.li2 = nn.Linear(36, 64)
        self.li3 = nn.Linear(64, 5)
        self.bn1 = nn.BatchNorm1d(36)
        self.bn2 = nn.BatchNorm1d(64)

    
    def forward(self, x):
        x = self.li1(x)
        self.bn1(x)
        x = self.li2(x)
        self.bn2(x)
        return self.li3(x)

In [12]:
net = linear().cuda()
x = torch.rand(2, 5).cuda()
print('input: ', x)
res = net(x)
print('output: ', res)

input:  tensor([[0.9049, 0.0338, 0.6938, 0.9239, 0.8570],
        [0.3320, 0.6364, 0.0343, 0.6900, 0.2239]], device='cuda:0')
output:  tensor([[-0.0715, -0.0005, -0.1904, -0.0049, -0.0508],
        [ 0.0174,  0.0156,  0.0123,  0.0386, -0.0521]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [13]:
def load_file(filename: str):
    '''
    导入指定的文件
    file: e.g. G:\深度学习\医疗\icentia-ecg\icentia-ecg\datasets\
    返回一个ndarray类型的数组，是文件的读取结果，尺寸为(50, 1048578)，最后一列记录当前一横行数据的采集者，范围0~10999
    '''
    # print("load file:", filename)
    data = pickle.load(gzip.open(filename))
    # print(type(data), data)
    idx = int(filename.split('/')[-1][:5])
    temp = idx * np.ones((data.shape[0], 1)) # (50, 1)
    data = np.concatenate([data, temp], axis=1)
    return data

In [18]:
file1 = 'datasets/00001_batched.pkl.gz'
file2 = 'datasets/03873_batched.pkl.gz'
res1 = load_file(file1)
print(f'读取{file1}', res1.shape)
res = load_file(file2)
print(f'读取{file2}', res.shape)

读取datasets/00001_batched.pkl.gz (50, 1048578)


EOFError: Compressed file ended before the end-of-stream marker was reached

In [12]:
a = torch.rand(16, 100, 512)
print('input: ', a.shape)
trans = nn.ConvTranspose1d(in_channels=2049, out_channels=2048*2, kernel_size=100, stride=1, dilation=1, groups=1, bias=True)
res = trans(a)
print('out: ', res.shape)

input:  torch.Size([16, 100, 512])


RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 3357081600 bytes.

In [6]:
a = [1, 100, 2049,  2048]
print(a[::-1])

[2048, 2049, 100, 1]


In [5]:
temp = torch.rand(2,1,3)
gemp = torch.rand(1,1,3)

temp = temp.cuda()
torch.cat([temp, gemp], dim=0)

print(temp.flatten(1).shape)
print(temp[:, :, -1].flatten())

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_cat)

In [6]:
a=np.array([i for i in range(8)]).reshape(2,4)
b=np.array([i for i in range(12,20)]).reshape(2,4)
c=np.array([i for i in range(24,32)]).reshape(2,4)
print(a, b, c)

[[0 1 2 3]
 [4 5 6 7]] [[12 13 14 15]
 [16 17 18 19]] [[24 25 26 27]
 [28 29 30 31]]


In [8]:
new_array=np.stack([a,b,c],axis=0)
print(new_array.shape, new_array)

(3, 2, 4) [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[12 13 14 15]
  [16 17 18 19]]

 [[24 25 26 27]
  [28 29 30 31]]]


In [35]:
def load_file(filename: str):
    '''导入指定的文件'''
    # print(">", filename)
    data = pickle.load(gzip.open(filename))
    print(data.shape)
    idx = int(filename.split('/')[-1][:5])
    temp = idx * np.ones((data.shape[0], 1)) # (50, 1)
    data = np.concatenate([data, temp], axis=1)
    print(data.shape)
    print(data[-5:])
    return data

In [36]:
file = load_file('datasets/00001_batched.pkl.gz')
# print(type(file))
# print(file.shape)

(50, 1048577)
(50, 1048578)
[[-0.01344722 -0.01344722 -0.01344722 ...  0.01344722  0.01344722
   1.        ]
 [ 0.02689444  0.02689444  0.04034166 ... -0.01344722 -0.01344722
   1.        ]
 [ 0.08068331  0.06723609  0.05378887 ...  0.04034166 -0.01344722
   1.        ]
 [-0.06723609 -0.04034166  0.02689444 ... -0.01344722 -0.01344722
   1.        ]
 [-0.01344722 -0.01344722 -0.01344722 ... -0.17481384 -0.06723609
   1.        ]]


In [6]:
x = np.random.rand(10)
print(x)
emb = x[None, None, :]
print(emb.shape)

[0.97758267 0.38901492 0.80206748 0.64696906 0.17957878 0.24085781
 0.79099158 0.21342157 0.47006748 0.98336314]
(1, 1, 10)


In [2]:
data, labels = getSubset(1200,
     embeddings_file='test_emb.csv.gz',
                                   labels_file='test_labels.csv.gz',
                                   seed=1,
                                   balanced='btype')


Loading cache G:\深度学习\医疗\icentia-ecg\icentia-ecg/.cache/1200_a3834861caaee2b35b754567601dc021_18536351bee99d761ac3a06f4b42d98c.pkl.gz


In [3]:
print(data)
print(labels)

                       0         1         2  ...      2046      2047    2048\r
id                                            ...                              
9000_0_90259   -0.094131 -0.094131 -0.094131  ... -0.013447 -0.040342 -0.053789
9000_0_774872   0.026894  0.013447  0.013447  ...  0.094131  0.067236  0.053789
9000_1_282137   0.000000  0.000000  0.013447  ... -0.026894 -0.040342 -0.026894
9000_1_617011  -0.053789 -0.053789 -0.053789  ...  0.026894  0.026894  0.026894
9000_1_830028   0.174814  0.174814  0.174814  ...  0.000000  0.000000  0.000000
...                  ...       ...       ...  ...       ...       ...       ...
9001_35_366486 -0.026894 -0.040342 -0.053789  ... -0.040342 -0.040342 -0.026894
9001_36_514000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
9001_37_64110   0.026894  0.053789  0.067236  ...  0.040342  0.040342  0.040342
9001_37_831753 -0.174814 -0.174814 -0.188261  ...  0.000000  0.000000  0.000000
9001_38_86383   0.040342  0.161367  0.36

In [6]:
args = {
    'model': 'knn',
    'num_examples': 1200,
    'label_type': 'bytes',
    'encode_method': None,
}

In [7]:
res = {"model": args['model'],
           "num_examples": int(args['num_examples']),
           "label_type": args['label_type'],
           "seed": int(233),
           "encode_method": args['encode_method']}

In [10]:
results = pd.read_csv('results.csv')

In [8]:
pd.DataFrame(res, index=[0])

model  num_examples label_type  seed encode_method
0   knn          1200      bytes   233          None